version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
      - restore_cache:
          key: i-dont-exist

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
