version: 2.1

executors:
  runner:
    machine: true
    resource_class: domparfitt/test

jobs:
  say-hello:
    executor: runner
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
      - restore_cache:
          key: i-dont-exist

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
